language: python
python:
- '3.5'
- '3.6'
notifications:
  email: false
env:
  matrix:
  - NUMPY="==1.10.1" TEST="PYTEST"
  - NUMPY="==1.11.3" TEST="PYTEST"
  - NUMPY="==1.12.1" TEST="PYTEST"
  - NUMPY="==1.13.1" TEST="PYTEST"
  - NUMPY="==1.14.3" TEST="PYTEST"
  - NUMPY="" TEST="FLAKE8"
addons:
  apt:
    packages:
    # fftw libraries
    - libfftw3-dev
    - libfftw3-3
install:
# numpy (must be installed before pyfftw)
- travis_retry pip install "numpy$NUMPY"
# libraries that do not have wheels on PyPI
- travis_retry pip install pyfftw
# everything else
- travis_retry pip install .
# coverage packages
- travis_retry pip install coverage codecov
- travis_retry pip install flake8
- pip freeze
script:
- set -ev
- if [ "${TEST}" == "PYTEST" ]; then
       coverage run --source=odtbrain ./setup.py test;
       coverage report -m;
       codecov;
  else
       flake8 odtbrain;
       flake8 examples;
       flake8 tests;
  fi;
deploy:
  provider: pypi
  user: "ci_qpi"
  password:
    secure: "gH1WKvMkdwiRbJOtk8Pbzbc3pZOHvrPeZFTVi8ai2n/qqAjE5sKk2Tyw61Lh7T0jL2Gf+hfUWRqkIDJRlvPGpCumPfJ40KYFXjeTldzY2gYbkVuvbJ6myyZAxZ1qzNowHHzG12rcUBpxNc37fN7gfZZp5RcRshSA9UKwISertvKXq6rEAqJsBbsFyVVtf8wC+rCsJcAtMaKKqM61a9D396vN83swwg7fLObVF7gcNul6mLqoP+ntbn16fn7+CWn/gAelCI8GAlWnZlXoz1hkau3U5iKyg0gOe+1l/2zoNURTdtjloYK63fl/F5CfofnKjIyIFArk6hqNtlYOm7deqr77KRyT50cJe2bJ8hsmlAK+Vm6Qilv8o9Ie3UXKkZfQOrQR9FllmKur6gNxt9pFJYRc4aId/MAG3XbrT5m1zxQr24SLxfjDyEvZP59zUcTTNNicKYBc+qS0OEL1VKy3eXX8qB5E7I5+fiSmMkMuEtOfKo2KwhvngT5Q9XhowTa6VfasZy/afZR2lL49aIADKiKPW6467MJBgibTApzEgYS7yfryHNKI5I/HA/1NEZFk3/hz/jHf7hdVCRYTdsJhM8uf2R6HZ/gMDfMSus5swI4zf+VhCb26bVP630oH88zTmJHQYvKpkb8C/dOVvX4L9Cx5hoVmuWEuzj0oDD0sK0w="
  on:
    tags: true
  distributions: "sdist bdist_wheel"
  skip_cleanup: true
  skip_existing: true

